apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: chakilams3/nginx-with-utils:latest
      ports:
        - containerPort: 80
    - name: sidecar
      image: curlimages/curl
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the sidecar container; sleep 30000"]
